export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const ABOUT_USER_REQUEST = 'ABOUT_USER_REQUEST'
export const ABOUT_USER_SUCCESS = 'ABOUT_USER_SUCCESS'
export const ABOUT_USER_FAILURE = 'ABOUT_USER_FAILURE'

export const ALL_USERS_REQUEST = 'ALL_USERS_REQUEST'
export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS'
export const ALL_USERS_FAILURE = 'ALL_USERS_FAILURE'

export const GET_ALL_TODOS_REQUEST = 'GET_ALL_TODOS_REQUEST'
export const GET_ALL_TODOS_SUCCESS = 'GET_ALL_TODOS_SUCCESS'
export const GET_ALL_TODOS_FAILURE = 'GET_ALL_TODOS_FAILURE'

export const GET_TODO_BY_ID_REQUEST = 'GET_TODO_BY_ID_REQUEST'
export const GET_TODO_BY_ID_SUCCESS = 'GET_TODO_BY_ID_SUCCESS'
export const GET_TODO_BY_ID_FAILURE = 'GET_TODO_BY_ID_FAILURE'

export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST'
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE'

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST'
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE'

export const UPDATE_TODO_REQUEST = 'UPDATE_TODO_REQUEST'
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS'
export const UPDATE_TODO_FAILURE = 'UPDATE_TODO_FAILURE'

