const LOGIN_REQUEST = 'LOGIN_REQUEST'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const LOGIN_FAILURE = 'LOGIN_FAILURE'

const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

const ABOUT_USER_REQUEST = 'ABOUT_USER_REQUEST'
const ABOUT_USER_SUCCESS = 'ABOUT_USER_SUCCESS'
const ABOUT_USER_FAILURE = 'ABOUT_USER_FAILURE'

const ALL_USERS_REQUEST = 'ALL_USERS_REQUEST'
const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS'
const ALL_USERS_FAILURE = 'ALL_USERS_FAILURE'

const GET_ALL_TODOS_REQUEST = 'GET_ALL_TODOS_REQUEST'
const GET_ALL_TODOS_SUCCESS = 'GET_ALL_TODOS_SUCCESS'
const GET_ALL_TODOS_FAILURE = 'GET_ALL_TODOS_FAILURE'

const GET_TODO_BY_ID_REQUEST = 'GET_TODO_BY_ID_REQUEST'
const GET_TODO_BY_ID_SUCCESS = 'GET_TODO_BY_ID_SUCCESS'
const GET_TODO_BY_ID_FAILURE = 'GET_TODO_BY_ID_FAILURE'

const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST'
const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE'

const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST'
const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'
const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE'

const UPDATE_TODO_REQUEST = 'UPDATE_TODO_REQUEST'
const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS'
const UPDATE_TODO_FAILURE = 'UPDATE_TODO_FAILURE'


export {LOGIN_REQUEST, LOGIN_SUCCESS, LOGIN_FAILURE,
        LOGOUT_REQUEST, LOGOUT_SUCCESS, LOGOUT_FAILURE,
        ABOUT_USER_REQUEST, ABOUT_USER_SUCCESS, ABOUT_USER_FAILURE,
        ALL_USERS_REQUEST, ALL_USERS_SUCCESS, ALL_USERS_FAILURE,
        GET_ALL_TODOS_REQUEST, GET_ALL_TODOS_SUCCESS, GET_ALL_TODOS_FAILURE,
        GET_TODO_BY_ID_REQUEST, GET_TODO_BY_ID_SUCCESS, GET_TODO_BY_ID_FAILURE,
        ADD_TODO_REQUEST, ADD_TODO_SUCCESS, ADD_TODO_FAILURE ,
        DELETE_TODO_REQUEST, DELETE_TODO_SUCCESS, DELETE_TODO_FAILURE,
        UPDATE_TODO_REQUEST, UPDATE_TODO_SUCCESS, UPDATE_TODO_FAILURE}